### ISSUE TITLE
Add support for Object Storage 

### ISSUE THREAD

**Issue by sergey-chechaev** [yandex-cloud/nodejs-sdk#11]
Please add support for Object Storage

**Comment by Devilpacks** [comment]
Есть пример настройки эндпоинта для s3 на AWS-SDK для JS. 
Возможно, для Object Storage можно настроить поменяв эндпоинт и выставив регион. 
Сам не пробовал.
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Endpoint.html

**Comment by nikolaymatrosov** [comment]
As Object Storage implements AWS S3 API, you can use AWS SDK to interact with Object Storage. E.g.
```js
const AWS = require('aws-sdk');
const config = {
    region: 'ru-central1',
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
};
const s3 = new AWS.S3({
    endpoint: process.env.S3_ENDPOINT ? process.env.S3_ENDPOINT : 'https://storage.yandexcloud.net',
    ...config,
});
await s3.createBucket({Bucket: request.name}).promise();
```
