### ISSUE TITLE
chore: MetadataTokenService does not extend the token by time and clean up the code from setTimeout

### ISSUE THREAD

**Issue by Zork33** [yandex-cloud/nodejs-sdk#128]
It is not clear that svc.getToken() will always return the initial value. Even if it is out of date

https://github.com/yandex-cloud/nodejs-sdk/blob/56bed7ce0039f76ade937a81b7666133c485038d/src/token-service/metadata-token-service.ts#L70 seems senseless

And creates the idea that the token will be updated over time

**Comment by DavyJohnes** [comment]
Duplicate https://github.com/yandex-cloud/nodejs-sdk/issues/89
