### ISSUE TITLE
Не получается сгенерировать iam-token по примеру из документации

### ISSUE THREAD

**Issue by omqmo** [yandex-cloud/nodejs-sdk#139]
В примере [Получить IAM-токен с помощью JWT](https://cloud.yandex.ru/docs/iam/operations/iam-token/create-for-sa#via-jwt) для nodejs 

```
var jose = require('node-jose');
var fs = require('fs');

var key = fs.readFileSync(require.resolve('<файл_закрытого_ключа>'));

var serviceAccountId = '<идентификатор_сервисного_аккаунта>';
var keyId = '<идентификатор_открытого_ключа>';
var now = Math.floor(new Date().getTime() / 1000);

var payload = { aud: "https://iam.api.cloud.yandex.net/iam/v1/tokens",
                iss: serviceAccountId,
                iat: now,
                exp: now + 3600 };

jose.JWK.asKey(key, 'pem', { kid: keyId, alg: 'PS256' })
    .then(function(result) {
        jose.JWS.createSign({ format: 'compact' }, result)
            .update(JSON.stringify(payload))
            .final()
            .then(function(result) {
                // result — это сформированный JWT.
            });
    });
```

на строчке 

```
jose.JWK.asKey(key, 'pem', { kid: keyId, alg: 'PS256' })
```

возникает ошибка - 

>  return Promise.reject(new Error("unsupported key type"));

Как это исправить?

**Comment by nikolaymatrosov** [comment]
Вам не нужно делать это самому, SDK выпустит JWT-токен за вас и обменяет его на IAM-токен. Просто инициализируйте SDK так
```typescript
const session = new Session({serviceAccountJson: {
    accessKeyId: data.id,
    privateKey: data.private_key,
    serviceAccountId: data.service_account_id,
  }});
```

**Comment by omqmo** [comment]
@nikolaymatrosov `data`, это тот самый генерируемый cli key.json? 

И вот еще что. Сомтрите, у меня есть облако - omcloud, в котором есть директория default. На вкладке `права доступа` (как я понял это вкладка отображает права доступа на ту самую директорию default) отображается мой сервисный аккаунт ombot, которому заданны права доступа api-gateway.admin. На вкладке `сервисные аккаунты` отображается все тот же аккаунт ombot, кликнув на который и перейдя уже пренадлежащую исключительно ему вкладку `права доступа` я вижу тот же аккаунт с теме же правами доступа. Вроде все должно работать. Но когда я выполняю - 

```
import {
  ListApiGatewayRequest,
} from "@yandex-cloud/nodejs-sdk/dist/generated/yandex/cloud/serverless/apigateway/v1/apigateway_service";


async function run(){
  const key = await import('../ombot-key.json').then(module => module.default)

  const session = new Session( {
    serviceAccountJson: {
      accessKeyId: key.id,
      privateKey: key.private_key,
      serviceAccountId: key.service_account_id,
    }
  } );

  const cloudService = session.client(serviceClients.ApiGatewayServiceClient);
 
  await cloudService.list( ListApiGatewayRequest.fromPartial( {
    folderId: `default`
  } ) );
}
```

то получаю - 

>     return new ClientError(path, error.code, error.details);
>          ^
>  ClientError: /yandex.cloud.serverless.apigateway.v1.ApiGatewayService/List PERMISSION_DENIED: Permission denied

В чем может быть дело?

**Comment by nikolaymatrosov** [comment]
> data, это тот самый генерируемый cli key.json?

Да.

> В чем может быть дело?

Субъекту, от имени которого выполняется вызов, в вашем случае это service account, не хватает прав. Скорее всего для этого вызова будет достаточно `api-gateway.viewer` [отсюда](https://cloud.yandex.ru/docs/api-gateway/security/#api-gateway-viewer).
По остальным ролям смотрите разделы «Управление доступом» в документации соответствующего сервиса.

В остальном этот issue не относится к SDK и скорее оффтопик.
