### ISSUE TITLE
13 INTERNAL Ошибка при вызове FunctionService.List

### ISSUE THREAD

**Issue by vermilion** [yandex-cloud/nodejs-sdk#14]
Пытаюсь получить functionId по её name
Как и написано в коментах **To get a function ID make a [FunctionService.List] request.**

```js
let functionListResponse = await functionService.list({
	folderId: inputs.folderId,
    filter: inputs.functionName
});
```

***Текущее поведение:***
При вызове постоянно выскакивает ошибка **##[error]13 INTERNAL: Internal**

***Ожидаемое поведение:***
Возврат списка функций

**Comment by monsterzz** [comment]
Простите за долгий ответ. В этом конкретном случае некорректно передавался фильтр. Валидное значение должно выглядеть как `name = "some-function-name"`

Сообщение об ошибке должно было исправиться
