### ISSUE TITLE
[Вопрос] существует ли единый способ управления бессерверными решениями?

### ISSUE THREAD

**Issue by omqmo** [yandex-cloud/nodejs-sdk#140]
Прошу прощения за вопрос в issues. Всего два вопроса.

1. @aws-sdk/lambda совместима в yandex functions?
2. @yandex-cloud/nodejs-sdk умеет делать тоже самое, что и @aws-sdk-client-s3 +  @aws-sdk/lambda?

Я вообще не могу загуглить инфу и найти хоть какие-то примеры по теме. Вообще ничего нет. Пытался сделать на текущей sdk и все закончилось головной болью от попытке разобраться с s3. Решил перейти на aws и за пау секунд сделал все, что было нужно. Дошел до функций и опять ступор. Очень надеюсь на помощь.

**Comment by nikolaymatrosov** [comment]
1. Скорее всего нет. Приведите пример использования.
2. Нет. Используйте AWS S3 SDK для работы с Object Storage.
