### ISSUE TITLE
Remove deprecated grpc and use grpc-js 

### ISSUE THREAD

**Issue by gespispace** [yandex-cloud/nodejs-sdk#18]
grpc now deprecated. https://www.npmjs.com/package/grpc#nodejs-grpc-library

**Comment by IlyaSemenov** [comment]
Any news on this? Besides everything else, the deprecated grpc package is not working on arm64 with esbuild.

**Comment by DavyJohnes** [comment]
Implemented in this release https://github.com/yandex-cloud/nodejs-sdk/releases/tag/v2.0.0-alpha.1.
