### ISSUE TITLE
AWS dependency

### ISSUE THREAD

**Issue by funcelot** [yandex-cloud/nodejs-sdk#20]
It is sad that you own samples uses AWS. Now it it clear that it is simplier just to use Node.js from original AWS SDK. Why you use AWS as a backend in samples? Or all your services maps to AWS in background? Strange.

**Comment by acoulon99** [comment]
Yandex's systems are independent from AWS (as far as I know), but it does seem like they're pretty 1 to 1 (even custom headers have the same x-amz prefix). If a system is already compatible with AWS, it's nice that it doesn't take much modification to be compatible with Yandex.

**Comment by nikolaymatrosov** [comment]
SDK v2 no longer depends on `aws-sdk`.
