### ISSUE TITLE
Update aws-sdk from v2 to v3 and save much space!

### ISSUE THREAD

**Issue by vitalets** [yandex-cloud/nodejs-sdk#30]
From aws [blog](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/welcome.html):
> The aws-sdk package adds about 40 MB to your application. Replacing varAWS = require("aws-sdk") with const {DynamoDB} = require("@aws-sdk/client-dynamodb") reduces that overhead to about 3 MB. Restricting the import to just the DynamoDB client and ListTablesCommand command reduces the overhead to less than 100 KB.

**Comment by nikolaymatrosov** [comment]
Have you tried this version with Yandex Cloud? It's possible that something changed and you won't be able to pass custom endpoint. One must not blindly bump package version.

**Comment by vitalets** [comment]
> One must not blindly bump package version.

Of course! :)

**Comment by nikolaymatrosov** [comment]
SDK v2 no longer depends on `aws-sdk`.
