### ISSUE TITLE
Как генерятся js/ts классы из proto файлов в этом репозитории?

### ISSUE THREAD

**Issue by vitalets** [yandex-cloud/nodejs-sdk#35]
Есть несколько тикетов про добавление новых сервисов (например #25  и #34), где кажется нужно просто сгенерить классы по существующим [proto файлам](https://github.com/yandex-cloud/cloudapi/tree/master/yandex/cloud/logging/v1). Я даже готов сделать пул-реквест. Но тут немного хитрая генерация, с разбивкой по файлам и добавлением [кастомного кода](https://github.com/yandex-cloud/nodejs-sdk/blob/964e6fa914792216a672d5dec4f811bc1005b78c/api/serverless/functions/v1/index.js#L311). Можете рассказать, как устроена генерация?
Для сравнения, в ydb-nodejs-sdk скрипт генерации [вот такой](https://github.com/ydb-platform/ydb-nodejs-sdk/blob/d799d32b4fa8135a058bcf7cff22643264602e93/package.json#L12), и с ним гораздо проще законтрибьютить.

**Comment by nikolaymatrosov** [comment]
Теперь скрипты генерации лежат тут. https://github.com/yandex-cloud/nodejs-sdk/tree/master/scripts

**Comment by DavyJohnes** [comment]
Если не хватает каких сервисов - создавайте Issue про это, будем стараться их разбирать как можно быстрее.
