### ISSUE TITLE
Как получить IAM токен для сервисного аккаунта без oauth / iam токена?

### ISSUE THREAD

**Issue by luixo** [yandex-cloud/nodejs-sdk#36]
Чтобы использовать метод create, нужен подобный код:
```ts
import {Session} from 'yandex-cloud';
import {IamTokenService} from 'yandex-cloud/api/iam/v1';

const iamService = new IamTokenService(new Session({}));
const {iamToken} = await iamService.create({jwt: '...'});
```
Однако в подобном случае, так как в сессии нет ни одного токена, библиотека пытается сходить в `http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token` и получает `ETIMEDOUT`.
Как правильно, если у меня есть jwt токен? Напрямую [по инструкции](https://cloud.yandex.ru/docs/iam/operations/iam-token/create-for-sa) - получается.

**Comment by luixo** [comment]
Так, но я ведь именно это и пытаюсь сделать - получить IAM токен по JWT-токену, но для этого нет метода в библиотеке. Хотелось бы метод, эквивалентный [вот этой](https://cloud.yandex.ru/docs/iam/operations/iam-token/create-for-sa) инструкции (с помощью которой я на данный момент и реализовал получение токена, с походом в эндпоинт вручную).

**Comment by nikolaymatrosov** [comment]
```typescript
import {IIAmCredentials} from '@yandex-cloud/nodejs-sdk/dist/types';
import fs from 'fs';
import {Session} from '@yandex-cloud/nodejs-sdk';

export interface ServiceAccountJsonFileContents {
  id: string;
  created_at: string;
  key_algorithm: string;
  service_account_id: string;
  private_key: string;
  public_key: string;
}

export function fromServiceAccountJsonFile(data: ServiceAccountJsonFileContents): IIAmCredentials {
  return {
    accessKeyId: data.id,
    privateKey: data.private_key,
    serviceAccountId: data.service_account_id,
  };
}

const ycSaJsonCredentials = fs.readFileSync('key.json').toString();

const serviceAccountJson = fromServiceAccountJsonFile(JSON.parse(ycSaJsonCredentials));

const session = new Session({serviceAccountJson});
```
