### ISSUE TITLE
TypeError in `node_modules/@grpc/grpc-js/build/src/channel.js`

### ISSUE THREAD

**Issue by DavyJohnes** [yandex-cloud/nodejs-sdk#56]
Может вы поможете разобраться, в чем же дело:)

Если комментирую TypeError тут `node_modules/@grpc/grpc-js/build/src/channel.js`, и оно работает, логи отправляются.
```
        if (!(credentials instanceof channel_credentials_1.ChannelCredentials)) {
			console.log(credentials);
			console.log(channel_credentials_1.ChannelCredentials);
            // throw new TypeError('Channel credentials must be a ChannelCredentials object');
        }
```
В консоли два объекта:
```
ComposedChannelCredentialsImpl {
  callCredentials: SingleCallCredentials { metadataGenerator: [Function (anonymous)] },
  channelCredentials: SecureChannelCredentialsImpl {
    callCredentials: EmptyCallCredentials {},
    rootCerts: null,
    privateKey: null,
    certChain: null,
    verifyOptions: {},
    connectionOptions: { secureContext: [SecureContext] }
  }
}
[class ChannelCredentials]
SecureChannelCredentialsImpl {
  callCredentials: EmptyCallCredentials {},
  rootCerts: null,
  privateKey: null,
  certChain: null,
  verifyOptions: {},
  connectionOptions: { secureContext: SecureContext { context: SecureContext {} } }
}
[class ChannelCredentials]
```

По удалял по одной все зависимости, пытаясь найти где же может быть коллизия. Но это не помогло:(

_Originally posted by @pltnm239 in https://github.com/yandex-cloud/nodejs-sdk/pull/50#issuecomment-1012081124_

**Comment by DavyJohnes** [comment]
@pltnm239 давайте тут продолжим? А покажите `npm ls @grpc/grpc-js`.

**Comment by pltnm239** [comment]
> @pltnm239 давайте тут продолжим? А покажите `npm ls @grpc/grpc-js`.

```
pltnm239@pltnm239-osx common-api % npm ls @grpc/grpc-js                           
common-api@0.1.0 /Users/pltnm239/Documents/frogly/common-api
├─┬ @google-cloud/text-to-speech@3.4.0
│ └─┬ google-gax@2.29.3
│   └── @grpc/grpc-js@1.5.0 
└─┬ yandex-cloud-v2@npm:yandex-cloud@2.0.0-alpha.3
  ├── @grpc/grpc-js@1.4.4 
  └─┬ nice-grpc@1.0.4
    └── @grpc/grpc-js@1.5.0  deduped
```

**Comment by DavyJohnes** [comment]
> Возможно, проблема из-за того что используется кастомный пакет `@grpc/grpc-js`. https://github.com/yandex-cloud/nodejs-sdk/blob/alpha/package.json#L25
> Оператор `instanceof` проверяет на то что объект экземпляр конкретного класса. А тут получается другой. Почему не использовать ванильный пакет из npm?

Потому что там есть патч, который еще не пророс в оригинальную репу.
В целом похоже что причина верна. Со дня на день в grpc-js опубликую мои изменения и я обновлю альфу.

**Comment by DavyJohnes** [comment]
https://github.com/grpc/grpc-node/pull/1993#issuecomment-1012602526

**Comment by DavyJohnes** [comment]
@pltnm239 кажется мне удалось победить эту проблему, попробуйте `@yandex-cloud/nodejs-sdk@2.0.0-alpha.7` (обратите внимание, имя пакета изменилось).

**Comment by pltnm239** [comment]
> @pltnm239 кажется мне удалось победить эту проблему, попробуйте `@yandex-cloud/nodejs-sdk@2.0.0-alpha.7` (обратите внимание, имя пакета изменилось).

Исходные: node v12.18.1, npm 6.14.5
Переустановил зависимости, это не помогло. После обновил npm до 7.21.1 (`npm i -g npm@7.21.1`)
Далее `npm i` удалив `package-lock`. Так заработало!
