### ISSUE TITLE
Как использовать API-ключ через SDK

### ISSUE THREAD

**Issue by fiftin** [yandex-cloud/nodejs-sdk#75]
Я создал API-ключ через дашборд:
![image](https://user-images.githubusercontent.com/914224/161690151-3127d52d-7651-4803-a4fe-e01b6cd4fa86.png)

Но я не смог найти в документации как его использовать в NodeJS SDK.

**Comment by nikolaymatrosov** [comment]
В SDK его не получится использовать. Его можно использовать только в:
[SpeechKit](https://cloud.yandex.ru/speechkit/concepts/auth)
[Translate](https://cloud.yandex.ru/translate/api-ref/authentication)
[Vision](https://cloud.yandex.ru/vision/api-ref/authentication)
Подробнее в [документации](https://cloud.yandex.ru/docs/iam/concepts/authorization/api-key)

Для авторизации в SDK вам надо выбирать третью опцию в этом меню.

**Comment by fiftin** [comment]
@nikolaymatrosov ,
 
Ясно, спасибо. Могу ли я создавать новый IAM-токен на каждый вызов API?

**Comment by nikolaymatrosov** [comment]
Вам не нужно об этом беспокоиться. При инициализации Session вы передаете параметры необходимые для авторизации, далее внутри создается инстанс сервиса имплементирующего  интерфейс `TokenService` и реализующего выбранный механизм получения токена. Он следит за тем чтобы токен был актуальным, кеширует его, а если время его жизни подходит к концу — перевыпускает.

**Comment by fiftin** [comment]
```
    const session = new Session({
      serviceAccountJson: {
        serviceAccountId: process.env.YC_SERVICE_ACCOUNT_ID,
        accessKeyId: process.env.YC_ACCESS_KEY_ID,
        privateKey: process.env.YC_PRIVATE_KEY,
      },
    });
```
Так?

**Comment by fiftin** [comment]
@nikolaymatrosov ,

нашел в другом ответе, спасибо. Видимо этой информации не хватает в документации...
