### ISSUE TITLE
S3 не поддерживается, я правильно понимаю?

### ISSUE THREAD

**Issue by horeca2** [yandex-cloud/nodejs-sdk#76]

**Comment by DavyJohnes** [comment]
S3 полностью совместим в плане API с aws, так что тут смело можно использовать sdk.
https://cloud.yandex.ru/docs/storage/tools/aws-sdk-go - тут пример на Go, но для nodejs все аналогично.

**Comment by DavyJohnes** [comment]
@horeca2 JFYI, https://github.com/yandex-cloud/nodejs-sdk/issues/77
