### ISSUE TITLE
Add Object Storage support

### ISSUE THREAD

**Issue by heyzling** [yandex-cloud/nodejs-sdk#77]
Please, add Object Storage support. Can't find it in current version (2.0.0)
https://cloud.yandex.com/en-ru/docs/storage/api-ref/Bucket/

**Comment by heyzling** [comment]
Found similar issue created 5 hour ago with answer
https://github.com/yandex-cloud/nodejs-sdk/issues/76

**Comment by heyzling** [comment]
Found S3 API's bug/restriction/incompability with Yandex Object Storage. It doesn't return list of buckets whenever you make requests by SA located in another folder/cloud.

I have task to discover all buckets throughout Organization, i.e. in all clouds, all folders. I tested [list-buckets method](https://docs.aws.amazon.com/cli/latest/reference/s3api/list-buckets.html) with AWS CLI and @aws-sdk/client-s3. This method returns buckets only if SA is located in the same folder and have appropriate roles. SA located in other folders/clouds cant see buckets, even if it has `admin` role on cloud or/and folder with buckets i want to list.

So, it seems, its important to add support for native Yandex API [gRPC BucketService](https://cloud.yandex.com/en-ru/docs/storage/api-ref/grpc/bucket_service) or [REST methods](https://cloud.yandex.com/en-ru/docs/storage/api-ref/Bucket/list). Only this methods allows to work with buckets from another folder.

What i tried:
1. AWS CLI: `aws --endpoint-url=https://storage.yandexcloud.net s3api list-buckets --query "Buckets[].Name"`
2. @aws-sdk/client-s3
```ts

import { defaultProvider } from "@aws-sdk/credential-provider-node"
import { S3Client, ListBucketsCommand, } from "@aws-sdk/client-s3";
import { log } from "../utils";

( async () => {
    
    try {

        // create client
        const client = new S3Client({
            region: "ru-central1",
            signingRegion: "ru-central1",
            endpoint: "https://storage.yandexcloud.net",
            forcePathStyle: true,            
            credentials: {
                accessKeyId: "SA STATIC KEY",
                secretAccessKey: "SA STATIC SECRET"
            },
        })
        
        // create command to execute
        const listBucketsCmd = new ListBucketsCommand({}) // there is no params for this command

        // call send for command
        const listBacketsResponse = await client.send(listBucketsCmd);
        // handle response
        const buckets = listBacketsResponse.Buckets
        if (buckets){
            for (const bucket of buckets) {
                log(`I am bucket ${bucket.Name}`)
            }
        } 
    }
    catch (error) {
        log (error)
    } finally {
        log ("I'm done.")
    }
})();

```

**Comment by DavyJohnes** [comment]
Release 2.1.0 which includes storage bucket service
