### ISSUE TITLE
Channel credentials must be a ChannelCredentials object

### ISSUE THREAD

**Issue by vladkolotvin** [yandex-cloud/nodejs-sdk#87]
```js
import {serviceClients, Session} from '@yandex-cloud/nodejs-sdk';

const session = new Session();
const logClient = session.client(serviceClients.LogIngestionServiceClient);
```

Ошибка:
```
/Users/vlad-kolotvin/podpison/backend/node_modules/nice-grpc/node_modules/@grpc/grpc-js/build/src/channel.js:81
            throw new TypeError('Channel credentials must be a ChannelCredentials object');
                  ^

TypeError: Channel credentials must be a ChannelCredentials object
    at new ChannelImplementation (/Users/vlad-kolotvin/podpison/backend/node_modules/nice-grpc/node_modules/@grpc/grpc-js/build/src/channel.js:81:19)
    at createChannel (/Users/vlad-kolotvin/podpison/backend/node_modules/nice-grpc/lib/client/channel.js:20:12)
    at Session.client (/Users/vlad-kolotvin/podpison/backend/node_modules/@yandex-cloud/nodejs-sdk/dist/session.js:65:55)
    at file:///Users/vlad-kolotvin/podpison/backend/src/logger.js:4:27
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async loadESM (node:internal/process/esm_loader:85:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)

Node.js v18.0.0

```

Кажется, что  в зависимостях используются несовместимые версии grpc-js.

**Comment by vladkolotvin** [comment]
workaround:
```json
{
  "type": "module",
  "dependencies": {
    "@yandex-cloud/nodejs-sdk": "^2.1.1"
  },
  "resolutions": {
    "@yandex-cloud/nodejs-sdk/nice-grpc/@grpc/grpc-js": "1.6.0"
  }
}

```

**Comment by nikolaymatrosov** [comment]
А полный список зависимостей можете предоставить?

**Comment by DavyJohnes** [comment]
> ```js
> ```js
> import {serviceClients, Session} from '@yandex-cloud/nodejs-sdk';
> 
> const session = new Session();
> const logClient = session.client(serviceClients.LogIngestionServiceClient);
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> Ошибка:
> /Users/vlad-kolotvin/podpison/backend/node_modules/nice-grpc/node_modules/@grpc/grpc-js/build/src/channel.js:81
>             throw new TypeError('Channel credentials must be a ChannelCredentials object');
>                   ^
> 
> TypeError: Channel credentials must be a ChannelCredentials object
>     at new ChannelImplementation (/Users/vlad-kolotvin/podpison/backend/node_modules/nice-grpc/node_modules/@grpc/grpc-js/build/src/channel.js:81:19)
>     at createChannel (/Users/vlad-kolotvin/podpison/backend/node_modules/nice-grpc/lib/client/channel.js:20:12)
>     at Session.client (/Users/vlad-kolotvin/podpison/backend/node_modules/@yandex-cloud/nodejs-sdk/dist/session.js:65:55)
>     at file:///Users/vlad-kolotvin/podpison/backend/src/logger.js:4:27
>     at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
>     at async Promise.all (index 0)
>     at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
>     at async loadESM (node:internal/process/esm_loader:85:5)
>     at async handleMainPromise (node:internal/modules/run_main:61:12)
> 
> Node.js v18.0.0
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> Кажется, что  в зависимостях используются несовместимые версии grpc-js.
> ```

У вас скорее всего неправильно package-lock.json сгенерился. Какая версия node\npm? Покажите вывод `npm ls @grpc/grpc-js`

**Comment by vladkolotvin** [comment]
> А полный список зависимостей можете предоставить?

```json
{
  "type": "module",
  "dependencies": {
    "@koa/router": "^10.1.1",
    "@yandex-cloud/nodejs-sdk": "^2.1.1",
    "koa": "^2.13.4",
    "luxon": "^2.3.2",
    "moment": "^2.29.3",
    "node-fetch": "^3.2.4",
    "telegraf": "^4.8.2",
    "uuid": "^8.3.2",
    "ydb-sdk": "^3.1.0"
  },
  "resolutions": {
    "@yandex-cloud/nodejs-sdk/nice-grpc/@grpc/grpc-js": "1.6.0"
  }
}
```

> У вас скорее всего неправильно package-lock.json сгенерился.

Пробовал перегенерить не помогло. Пробовал и yarn и npm.

> Какая версия node\npm?

```
% node --version
v18.0.0

% npm --version
8.6.0

 % yarn --version
1.22.18
```

> Покажите вывод npm ls @grpc/grpc-js

```
% npm ls @grpc/grpc-js
backend@ /Users/vlad-kolotvin/podpison/backend
├─┬ @yandex-cloud/nodejs-sdk@2.1.1
│ ├── @grpc/grpc-js@1.6.0
│ └─┬ nice-grpc@1.0.6
│   └── @grpc/grpc-js@1.6.0 deduped
└─┬ ydb-sdk@3.1.1
  ├── @grpc/grpc-js@1.6.7
  └─┬ @yandex-cloud/nodejs-sdk@2.1.0
    └── @grpc/grpc-js@1.6.0

```

**Comment by vladkolotvin** [comment]
А вот, что будет, если убрать resolutions: 

```
% npm ls @grpc/grpc-js                
backend@ /Users/vlad-kolotvin/podpison/backend
├─┬ @yandex-cloud/nodejs-sdk@2.1.1
│ ├── @grpc/grpc-js@1.6.0
│ └─┬ nice-grpc@1.0.6
│   └── @grpc/grpc-js@1.6.7
└─┬ ydb-sdk@3.1.1
  ├── @grpc/grpc-js@1.6.7
  └─┬ @yandex-cloud/nodejs-sdk@2.1.0
    └── @grpc/grpc-js@1.6.0
```

**Comment by DavyJohnes** [comment]
> А вот, что будет, если убрать resolutions:
> 
> ```
> % npm ls @grpc/grpc-js                
> backend@ /Users/vlad-kolotvin/podpison/backend
> ├─┬ @yandex-cloud/nodejs-sdk@2.1.1
> │ ├── @grpc/grpc-js@1.6.0
> │ └─┬ nice-grpc@1.0.6
> │   └── @grpc/grpc-js@1.6.7
> └─┬ ydb-sdk@3.1.1
>   ├── @grpc/grpc-js@1.6.7
>   └─┬ @yandex-cloud/nodejs-sdk@2.1.0
>     └── @grpc/grpc-js@1.6.0
> ```

Это очень странно, почему-то npm решил выбрать разные версии `@grpc/grpc-js` в ветке `@yandex-cloud/nodejs-sdk`. А как вы генерили `package-lock`? А попробуйте удалить его вообще и сделать `npm i`? Если не поможет, то попробуйте версию nodejs как указано в https://github.com/yandex-cloud/nodejs-sdk/blob/master/.nvmrc

**Comment by fiftin** [comment]
Такая же проблема

**Comment by DavyJohnes** [comment]
> Такая же проблема
> 
> node v18.10.0
> 
> ```
> `-- @yandex-cloud/nodejs-sdk@2.2.1
>   +-- @grpc/grpc-js@1.6.0
>   `-- nice-grpc@1.0.6
>     `-- @grpc/grpc-js@1.7.1
> ```
> 
> Похоже это происходит только для 18 версии ноды, для 16 все ок.
> 
> Вроде бы все понятно, но за 4 месяца так и не исправили... Никому не нужно что-ли?)

Воспроизводится не стабильно. Закономерность определенную так и не удалось выяснить.

**Comment by fiftin** [comment]
> > Такая же проблема
> > 
> > node v18.10.0
> > 
> > ```
> > `-- @yandex-cloud/nodejs-sdk@2.2.1
> >   +-- @grpc/grpc-js@1.6.0
> >   `-- nice-grpc@1.0.6
> >     `-- @grpc/grpc-js@1.7.1
> > ```
> > 
> > Похоже это происходит только для 18 версии ноды, для 16 все ок.
> > 
> > Вроде бы все понятно, но за 4 месяца так и не исправили... Никому не нужно что-ли?)
> 
> Воспроизводится не стабильно. Закономерность определенную так и не удалось выяснить.
> Можете, пожалуйста, репу накидать где стабильно воспроизводится?

К сожалению это приватный репозиторий

**Comment by nikolaymatrosov** [comment]
> Воспроизводится не стабильно. Закономерность определенную так и не удалось выяснить.
Может просто убрать жесткую привязку версии `@grpc/grpc-js`?

**Comment by DavyJohnes** [comment]
> > > Такая же проблема
> > > node v18.10.0
> > > ```
> > > `-- @yandex-cloud/nodejs-sdk@2.2.1
> > >   +-- @grpc/grpc-js@1.6.0
> > >   `-- nice-grpc@1.0.6
> > >     `-- @grpc/grpc-js@1.7.1
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Похоже это происходит только для 18 версии ноды, для 16 все ок.
> > > Вроде бы все понятно, но за 4 месяца так и не исправили... Никому не нужно что-ли?)
> > 
> > 
> > Воспроизводится не стабильно. Закономерность определенную так и не удалось выяснить.
> > Можете, пожалуйста, репу накидать где стабильно воспроизводится?
> 
> К сожалению это приватный репозиторий.
> 
> У вас жёстко прописаны версии пакетов, не удивительно что возникает конфликт.

Жестко прописаны только major/minor.

**Comment by vladkolotvin** [comment]
> Но вообще супер странно, почему это некоторые версии npm решили ставить @grpc/grpc-js@1.7.1, если в nice-grpc@1.0.6 явно написано @grpc/grpc-js: ^1.5.1.

Вроде всё верно. 1.7.1 > ^1.5.1
Разве знак ^ не говорит, что можно взять версию не ниже указанной?

**Comment by DavyJohnes** [comment]
> > Но вообще супер странно, почему это некоторые версии npm решили ставить @grpc/grpc-js@1.7.1, если в nice-grpc@1.0.6 явно написано @grpc/grpc-js: ^1.5.1.
> 
> Вроде всё верно: 1.7.1 > ^1.5.1 Разве знак ^ не говорит, что можно взять версию не ниже указанной?

Да, сорри, с `~` перепутал :)

**Comment by DavyJohnes** [comment]
@vladkolotvin @fiftin попробуйте `@2.2.2`
