### ISSUE TITLE
What happened to InvokeService in v2?

### ISSUE THREAD

**Issue by gusev-genotek** [yandex-cloud/nodejs-sdk#88]
I used to call my private yandex function like so:

```
            const iamToken = ...;
            const session = new Session({ iamToken: iamToken });
         
            const invokeService = new InvokeService(session);
            const YANDEX_FUNC_ID = 'MY_FUNCTION_ID';

            const payload = {
                'httpMethod': 'GET',
                'multiValueQueryStringParameters': {PARAM1': 'PARAM1, PARAM2: 'PARAM2'},
                'body': {},
            };
            const resp = await invokeService.invoke(YANDEX_FUNC_ID, payload, config.yandex_function_tag);
```
Now, that InvokeService is vanished, what is the migration path from the code above to using @yandex-cloud/nodejs-sdk?

**Comment by DavyJohnes** [comment]
> There is no gRPC service for invoking functions. It has always been a simple HTTPS call with the authorization header. So you can use the request lib of your choice to make this call yourself.

Exactly. Call function is just calling http URL of function (take a look at [code](https://github.com/yandex-cloud/nodejs-sdk/blob/v1.4.3/lib/serverless/functions/v1/invoke.js)). So current path is:
1. Get function URL using nodejs-sdk
2. Call this URL using any http client

**Comment by gusev-genotek** [comment]
@nikolaymatrosov @DavyJohnes Thanks! I am following [example](https://github.com/yandex-cloud/nodejs-sdk/blob/master/examples/functions.ts) in order to get function URL, but am using AIM token instead of oauthToken (as in my initial example above):

```
const session = new Session({ iamToken: iamToken });
```
and then 
```
const client = session.client(serviceClients.FunctionServiceClient);
```
throws _TypeError: Channel credentials must be a ChannelCredentials object_

Can I use iamToken to get Session object as I used to?

**Comment by nikolaymatrosov** [comment]
This error occurs due to different versions of the `@grpc/grpc-js` package in node modules. You can find the workaround here. https://github.com/yandex-cloud/nodejs-sdk/issues/87#issuecomment-1158235255

**Comment by DavyJohnes** [comment]
> This error occurs due to different versions of the `@grpc/grpc-js` package in node modules. You can find the workaround here. [#87 (comment)](https://github.com/yandex-cloud/nodejs-sdk/issues/87#issuecomment-1158235255)
I would suggest to regenerate `package-lock.json` and figure out which versions of `@grpc/grpc-js` are in it.
